import Web3 from "web3";

const getContract = async () => {
  const web3 = new Web3(window.ethereum);
  const contractAddress = "0xA3DF8bf6688F93Ad7D750b6B3aA9B26e9F1E8421"; 
  const contractABI = [[{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"id","type":"uint256"},
                                                     {"indexed":false,"internalType":"string","name":"title","type":"string"},
                                                     {"indexed":false,"internalType":"string","name":"description","type":"string"},
                                                     {"indexed":false,"internalType":"string","name":"content","type":"string"},
                                                     {"indexed":false,"internalType":"address","name":"author","type":"address"},
                                                     {"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"NewsSubmitted","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"id","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"votes","type":"uint256"}],"name":"NewsVoted","type":"event"},{"constant":true,"inputs":[],"name":"getAllNews","outputs":[{"internalType":"uint256[]","name":"","type":"uint256[]"},{"internalType":"string[]","name":"","type":"string[]"},{"internalType":"string[]","name":"","type":"string[]"},{"internalType":"string[]","name":"","type":"string[]"},{"internalType":"address[]","name":"","type":"address[]"},{"internalType":"uint256[]","name":"","type":"uint256[]"},{"internalType":"uint256[]","name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"}],"name":"getNews","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"string","name":"title","type":"string"},{"internalType":"string","name":"description","type":"string"},{"internalType":"string","name":"content","type":"string"},{"internalType":"address payable","name":"author","type":"address"},{"internalType":"uint256","name":"votes","type":"uint256"},{"internalType":"uint256","name":"timestamp","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"newsArticles","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"string","name":"title","type":"string"},{"internalType":"string","name":"description","type":"string"},{"internalType":"string","name":"content","type":"string"},{"internalType":"address payable","name":"author","type":"address"},{"internalType":"uint256","name":"votes","type":"uint256"},{"internalType":"uint256","name":"timestamp","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"newsCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"string","name":"_title","type":"string"},{"internalType":"string","name":"_description","type":"string"},{"internalType":"string","name":"_content","type":"string"}],"name":"submitNews","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"}],"name":"voteNews","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]];
  const contract = new web3.eth.Contract(contractABI, contractAddress);
  return contract;
};

export default getContract;
